name = "tarkeeb-pro-frontend"
main = "cloudflare/worker.js"
compatibility_date = "2026-03-26"

[assets]
binding = "ASSETS"
directory = "./build"

[[services]]
binding = "EDGE_API"
service = "tarkeeb-pro-edge-api"

[vars]
API_ORIGIN = "https://tarkeeb-pro-edge-api.bobkumeel.workers.dev"
