name = "tarkeeb-pro-edge-api"
main = "src/index.js"
compatibility_date = "2026-03-26"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false
routes = [
  { pattern = "api.kumeelalnahab.com", custom_domain = true }
]

[vars]
CORS_ALLOWED_ORIGINS = "http://localhost:3000,http://127.0.0.1:3000,http://localhost:8501,http://127.0.0.1:8501,http://localhost,http://127.0.0.1,https://localhost,https://127.0.0.1,capacitor://localhost,https://kumeelalnahab.com,https://www.kumeelalnahab.com,https://api.kumeelalnahab.com,https://kemo-eight.vercel.app"
WEB_PUSH_PUBLIC_KEY = "BJDe1im_oVNRMdPrjtBjE7qwlb-CJUDIxxc_Dp-mhPwuiuSgTHcFxWgS3MX-gyVyy3YPMS8nGQ6YaJIb1rrGgyo"
WEB_PUSH_CONTACT_EMAIL = "ops@tarkeebpro.sa"
INBOUND_EMAIL_ALLOWED_TO = "hashimaldrweish@kumeelalnahab.com,bookings@kumeelalnahab.com,customerservice@kumeelalnahab.com,info@kumeelalnahab.com"
INBOUND_EMAIL_FORWARD_TO = "kumeelalnahab@gmail.com"

[[d1_databases]]
binding = "DB"
database_name = "tarkeeb_pro_db"
database_id = "d25b479d-41f9-4775-87ca-4a2d60d87e30"

[[send_email]]
name = "SEND_EMAIL"
allowed_sender_addresses = [ "hashimaldrweish@kumeelalnahab.com", "bookings@kumeelalnahab.com", "customerservice@kumeelalnahab.com", "info@kumeelalnahab.com" ]
allowed_destination_addresses = [ "kumeelalnahab@gmail.com" ]

[[queues.producers]]
binding = "IMPORT_JOBS_QUEUE"
queue = "tarkeeb-import-jobs"

[[queues.consumers]]
queue = "tarkeeb-import-jobs"
max_batch_size = 1
max_batch_timeout = 5
