name = "rentit-edge-api"
main = "src/index.js"
compatibility_date = "2026-03-26"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
CORS_ALLOWED_ORIGINS = "http://localhost:3000,http://127.0.0.1:3000,http://localhost,http://127.0.0.1,https://localhost,https://127.0.0.1,capacitor://localhost,https://tarkeeb-pro-frontend.bobkumeel.workers.dev"
ACCESS_AUD = "282d6bbb5c79e6fa216dc031838ec36e641595f0c62f5ee0732e6d2f264eefa6"
ACCESS_JWKS_URL = "https://bobkumeel.cloudflareaccess.com/cdn-cgi/access/certs"

[[d1_databases]]
binding = "DB"
database_name = "tarkeeb_pro_db"
database_id = "d25b479d-41f9-4775-87ca-4a2d60d87e30"
